// vue/examples/demo/src/App.vue
<script setup>
import Moon from 'here-comes-the-moon';
import { nextTick, ref, watch } from 'vue';

const childRef = ref(null);
const moonRef2 = ref(null);
const loading = ref(false);
const more = ref([]);

watch(loading, v => {
  nextTick(() => {
    if (v) {
      moonRef2.value.play();
      setTimeout(() => {
        loading.value = false;
        more.value = [...more.value, 'more!'];
        moonRef2.value.stop();
      }, 1998);
    }
  })
});

function play() {
  childRef.value.play();
}
function toggle() {
  childRef.value.toggle();
}
function stop() {
  childRef.value.stop();
}
</script>

<template>
  <main class="flex min-h-screen flex-col items-center py-8 box-border gap-8">
    <!-- <Moon ref="childRef" :moons="['🕛', '🕐', '🕑', '🕒', '🕓', '🕔', '🕕', '🕖', '🕗', '🕘', '🕙', '🕚']" :breakI="[0, 6]"  /> -->
    <Moon ref="childRef" />
    <div class="flex gap-3">
      <button @click="play">play</button>
      <button @click="stop">stop</button>
      <button @click="toggle">toggle</button>
      <button @click="loading=true">load more</button>
    </div>
    <Moon v-if="loading" class="!fixed top-4 left-4" ref="moonRef2" :breakI="null" />
    <div>
      <div v-for="(m, i) in more" class="text-5xl" :key="i">{{m}}</div>
    </div>
  </main>
</template>

// react/examples/demo/app/page.js
"use client"

import Moon from "here-comes-the-moon-react";
import { useEffect, useRef, useState } from "react";

export default function Home() {
  const moonRef = useRef();
  const moonRef2 = useRef();
  const [more, setM] = useState([]);

  const [loading, setL] = useState(false);

  useEffect(() => {
    if (loading) {
      moonRef2.current.play();
      setTimeout(() => {
        setL(false);
        setM(v => [...v, 'more!'])
        moonRef2.current.stop();
      }, 1998);
    }
  }, [loading]);

  return (
    <main className="flex min-h-screen flex-col items-center py-8 box-border gap-8">
      <Moon ref={moonRef} breakI={[0, 4]} moonClassName="text-3xl" />
      <div style={{ display: "flex", gap: 9 }}>
        <button onClick={() => {
          moonRef.current.play();
        }}>play</button>
        <button onClick={() => {
          moonRef.current.stop();
        }}>stop</button>
        <button onClick={() => {
          moonRef.current.toggle();
        }}>toggle</button>
        <button onClick={() => { setL(true) }}>load more</button>
      </div>
      {loading && <div className="fixed top-4 left-4"><Moon ref={moonRef2} breakI={null} moonClassName="text-xl" frameTm={80} dur={196} /></div>}
      <div>
        {more.map((m, i) => <div className="text-5xl" key={i}>{m}</div>)}
      </div>
    </main>
  );
}
